apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test123-mnce
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test123-mnce
    app.kubernetes.io/part-of: eclipse-vertx-booster
  name: test123-mnce
  namespace: rgarg-1-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: test123-mnce
    weight: null
status: {}
